// <auto-generated />
namespace Udemy_Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updadeMovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updadeMovie));
        
        string IMigrationMetadata.Id
        {
            get { return "202003271644293_updadeMovie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
